---
title: "myBookQ"
author: "Alicia Brown"
output: 
  flexdashboard::flex_dashboard:
    theme: yeti
    orientation: rows
    social: [ "twitter", "facebook", "linkedin"]
    source_code: "https://github.com/aliciatb/mybookq"
    favicon: favicon-q.png
runtime: shiny
---

```{r setup}
#options(shiny.sanitize.errors = T)

library(dplyr)
library(ggplot2)
library(lubridate)
library(flexdashboard)
library(httr)
library(jsonlite)
library(stringr)
library(tidyr)
library(tidytext)
library(wordcloud)
require(wesanderson)

favorite_authors <- "Louise Penny,Fred Vargas,Kate Atkinson,Nancy Atherton,Denisa Mina,Val McDermid,Deborah Crombie,Jussi Adler-Olsen,ML Longworth,Lisa Scottoline,Jacqueline Winspear,Stella Rimington,Mike Lawson,Arnaldur Indridason,Susan Hill,Susan Elia MacNeal,Elly Griffiths,M. L. Longworth,Helene Tursten,Camilla Lackberg,David Lagercrantz,Tana French,Nevada Barr"
```

```{r}
authorURL <- function(author){
  google_key <- 'AIzaSyAwJfF6E3x_UkuAj4ahufzJKwOHZIaEql0'
  
  # currently pulling last author, need to iterate and rbind
  author_name <- str_split(author," ", simplify = TRUE)
  
  author_first <- author_name[1]
  author_last <- author_name[2]
  
  order_by <- 'newest'
  # https://www.googleapis.com/books/v1/volumes?q=inauthor:Fred%20Vargas&langRestrict=en&orderBy=newest&printType=books&maxresults=40&prettyPrint=true&key=AIzaSyAwJfF6E3x_UkuAj4ahufzJKwOHZIaEql0
  url <- paste0("https://www.googleapis.com/books/v1/volumes?q=inauthor:",author_first,"+",author_last,"&langRestrict=en&orderBy=",order_by,"&printType=books&maxresults=40&prettyPrint=true&key=",google_key)
  url
}
```

```{r}
# Reactive data available for all shiny modules
getData <- reactive({
  # 1. Get the comma delimited string of authors from input$author_query
  
  author_query <- c(input$author_query)
  #author_query <- "Louise Penny,Fred Vargas"
  authors <- str_split(author_query,",",simplify = T)
  
  date_from <- input$dateRange[1]
  date_to = input$dateRange[2]
  
  books <- tibble()
  
  # 2. Get books for each author, filter by author name, combine data
  for(author in authors){
    author_url <- authorURL(author)
    data <- fromJSON(URLencode(author_url),simplifyDataFrame = TRUE)
    
    volume_info <- data$items$volumeInfo
    access_info <- data$items$accessInfo
    search_info <- data$items$searchInfo
    sale_info <- data$items$saleInfo
    
    if (is.null(volume_info) == FALSE){
      raw_data <- cbind(volume_info,sale_info,search_info) %>%
        # adding author here since results returns as list
        mutate(name = author) %>%
        # handle year and year-month dates
        mutate(
          publishedDate = case_when(
          str_length(publishedDate) == 4 ~ paste0(publishedDate,"-01-01"),
          str_length(publishedDate) == 7 ~ paste0(publishedDate,"-01"),
          TRUE ~ publishedDate)) %>%
        # filter by date control
        filter(publishedDate >= date_from) %>%
        filter(publishedDate <= date_to) %>%
        select(title,name,publishedDate,publisher,description,saleability) %>%
        mutate(description_length = str_length(description)) %>%
        arrange(desc(publishedDate))
      raw_data
      
      books <- rbind(books, raw_data)
    }
  }
  books

})
```

Inputs {.sidebar data-width=300}
-----------------------------------------------------------------------

Check for new releases!

```{r}
textAreaInput("author_query", label = "Favorite Authors:", value = favorite_authors, rows=10, resize = "vertical")
```

```{r}
  dateRangeInput('dateRange',
      label = 'Date range:',
      start = Sys.Date() - 30, end = Sys.Date() + 365
    )
```

Row {.tabset}
-----------------------------------------------------------------------

### New Book Results
    
```{r fig.width=18, fig.height=8}

renderTable({
  
  data_view <- getData()
   
  if(length(data_view) > 0){
    data_view %>%
      group_by(name,title,publishedDate) %>%
      summarize(count = n()) %>%
      select(title, publishedDate) %>%
      arrange(publishedDate)
  }
  else{
    paste0('No results found for ',input$author_query)
  }
}
# allow html hyperlinks
, sanitize.text.function = function(x) x)
```


  
```{r fig.width=18, fig.height=10, eval = FALSE}
# ### Upcoming Book Review Description Cloud
pal <- wes_palette("Darjeeling1")
		
renderPlot({
  
  data_view <- booksData()
  
  if(length(data_view) > 0){
    original_reviews <- data_view %>%
      # show the upcoming books (likely 1)
      filter(publishedDate > now()) %>%
      select(title, description)
      
    tidy_reviews <- original_reviews %>%
      unnest_tokens(word, description)
  
    if(length(tidy_reviews) > 0){
    
      tidy_reviews %>%
      anti_join(stop_words) %>%
      count(word) %>%
      with(wordcloud(word, n, max.words = 100, colors=pal, scale=c(3.0,0.5), rot.per=0.1))
      
    }
  }
})
```



```{r eval=F}
### Authors
renderTable({
  data_view <- booksData()
   
  if(length(data_view) > 0){
    data_view %>%
      select(authors) %>%
      filter(authors == input$author_query)
  }else{
    paste0('No results found for ',input$author_query)
  }
})

```
